name: restart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - ipywidgets
  - ipympl
  - ipyvuetify
  - ipysheet
  - scipy
  - altair
  - qgrid
  - xlrd
  - confuse
  - bqplot
  - h5py
  - pyomo
  - ipyvolume
  - pip
  - pip:
    - restart==2.6.7
    - tables
    - restart_datasets
    - voila

